name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image for 'vote' microservice
    - name: Build and push 'vote' microservice Docker image
      run: |
        docker build -t demiesp/vote:latest ./vote
        docker push demiesp/vote:latest

    # Build and push Docker image for 'result' microservice
    - name: Build and push 'result' microservice Docker image
      run: |
        docker build -t demiesp/result:latest ./result
        docker push demiesp/result:latest

    # Build and push Docker image for 'worker' microservice
    - name: Build and push 'worker' microservice Docker image
      run: |
        docker build -t demiesp/worker:latest ./worker
        docker push demiesp/worker:latest

  # Manual step to update Kubernetes manifests with new image versions
  update-k8s-manifests:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update Kubernetes manifests with new image tags
      run: |
        sed -i 's|demiesp/vote:.*|demiesp/vote:latest|' k8s-specifications/vote-deployment.yaml
        sed -i 's|demiesp/result:.*|demiesp/result:latest|' k8s-specifications/result-deployment.yaml
        sed -i 's|demiesp/worker:.*|demiesp/worker:latest|' k8s-specifications/worker-deployment.yaml
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git commit -am "Update Kubernetes manifests with new image tags"
        git push

